[workspace]
resolver = "2"
members = [
    "dearx_app",
    "dearx_edit_model",
    "dearx_editor/src-tauri",
    "dearx_gfx/dearx_gfx",
    "dearx_gfx/dearx_viewer",
    "dearx_serialization",
    "dearx_presentation/sycamore",
    "dearx_presentation/dearx_tool_windows",
    "dearx_macro",
    "dearx_workspace",
]
